//
// Created by tefx on 10/22/19.
//

#ifndef LIBTCY_ERROR_H
#define LIBTCY_ERROR_H

#define SUCCEED 0
#define ERROR_ALLOC_CELL_MISSING_LOCATION_INFO 1
#define ERROR_UNKNOWN_BOX_SIZE 2
#define ERROR_CANNOT_FIND_STACKING_AXIS 3
#define ERROR_INVALID_LOCATION 4

#endif //LIBTCY_ERROR_H
